"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
style = "green"

[conda]
format = "via [$symbol $environment]($style) "

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment i being set to "➜" with the color "bold green"
format = "[❯ ](green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
